version: "3.7"
volumes:
  database:
services:
  db:
    image: mysql:latest
    container_name: hibernate
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=senharoot
      - MYSQL_DATABASE=banco
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha
